version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - gocyclo
  settings:
    gocyclo:
      min-complexity: 15
    misspell:
      locale: US
  exclusions:
    presets: []

formatters:
  enable:
    - gofmt
