version: 2

builds:
  - main: ./cmd/agentws
    binary: agentws
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

release:
  extra_files:
    - glob: agentws-install.sh

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
